version: '3.8'

services:
  go_app:
    image: rococo44/go_app:latest
    container_name: go_app
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - LOKI_URL=http://loki:3100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /Users/aanlebedev/BAREbuXxX_1337/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - app_network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
